### ISSUE TITLE
Medical Requirements

### ISSUE THREAD

**Issue by izwick-schachter** [CrowdRescueHQ/CrowdRescue#10]
The medical people would like a couple things:

- [x] Editable, private field that's only viewable/editable for people with the medical role called "Chart Code"
- [x] Medical-only comments, only viewable/creatable for people with the medical role. Possibly filterable on the client side.
- [x] A special triage status that only medical can edit but is publicly viewable. The options are: Medevac, Emergent, Urgent, Semi-Urgent. Changes to this status and the user who made those changes needs to be logged and viewable by those with the medical role.

**Comment by ArtOfCode-** [comment]
These'll be visible to medical *and developers*, but they can be done pretty easily.

**Comment by izwick-schachter** [comment]
That's fine. I talked to one of the medical people, and nothing they'll be putting in there should give us HIPAA issues.

**Comment by izwick-schachter** [comment]
@ArtOfCode- If I make a route to update the medical triage status in the rescue request controller (which includes AccessLogger), will it log the user who edited it, the previous value, and the new value in a format where it's easily displayable?

**Comment by ArtOfCode-** [comment]
Nope. AccesLoggeris literally just who viewed what, when, and via what action. You also need to add the action to log_actions if you want it to create those logs.
