### ISSUE TITLE
Link expansion

### ISSUE THREAD

**Issue by izwick-schachter** [CrowdRescueHQ/CrowdRescue#11]
For twitter links that are stored, we should provide an embedded version of that tweet on the view for the `RescueRequest`.

**Comment by ArtOfCode-** [comment]
That's labelled as a Twitter handle, not a Tweet link...

**Comment by izwick-schachter** [comment]
Oh. In that case, we should add a twitter link field first, because that's in the spreadsheet and it's useful info.
