### ISSUE TITLE
Track Contacts

### ISSUE THREAD

**Issue by izwick-schachter** [CrowdRescueHQ/CrowdRescue#16]
We should add a table, similar to case notes, where every time a person is contacted we can track how they were contacted, when, by whom, and what the conclusion of that contact (or failed contact attempt) was.

**Comment by ArtOfCode-** [comment]
We can use case notes for this. We can add a structured way to input the contact attempt details, but there's no need for a new model.

**Comment by izwick-schachter** [comment]
But what's the harm of a new model? Having a new model would make it much more searchable, and flexible if we want to work with that data in the future.

**Comment by ArtOfCode-** [comment]
Valid point. Okay, new model it is :)

**Comment by izwick-schachter** [comment]
@ArtOfCode- For the new model, I'm thinking:

- timestamps
- user (created by)
- rescue_request
- medium (text) (call, text, etc.)
- outcome (no response, left voicemail, etc.)
- details

How does that sound to you?

**Comment by ArtOfCode-** [comment]
Sounds about right. Generate command: `rails g model ContactAttempt user:references rescue_request:references medium:string outcome:string details:text`

**Comment by ArtOfCode-** [comment]
5e70a91ed781f90524f0e7d80e304c0d488aa1ff
