### ISSUE TITLE
Incident Updates/Suggested Edits

### ISSUE THREAD

**Issue by izwick-schachter** [CrowdRescueHQ/CrowdRescue#18]
We need to fill the need of having a "suggested edits" queue, where one group of volunteers can fill out an update form and other volunteers can process it. This could work like suggested edits or it could be a form which feeds a queue. Both would be similar, but the latter would require a new table. We need to get more feedback about this.

Each edit should get logged and possible have an attached note or reason. (Could be built through case notes, could be separate).

**Comment by izwick-schachter** [comment]
These can be suggested edits. @ArtOfCode- Should we make a new model for this? Or add a `edit_for` field to the RescueRequests model?

**Comment by ArtOfCode-** [comment]
Good question. A new model seems overkill, but on the other hand if we have an edit_for field then we have to filter out suggested edits everywhere else. I think probably the field on RescueRequests? That makes most sense to me at the moment.

**Comment by izwick-schachter** [comment]
We could do some model magic and hide all the `edit_for` field from the RescueRequest model and make a new pseudo model for SuggestedEdits

**Comment by ArtOfCode-** [comment]
We could, yeah. Go for it if you've got ideas on how to do it.

**Comment by izwick-schachter** [comment]
Oh, whoops, I deleted that comment before I saw your reply. That sounds complex and like a pain in the neck, so I'm going to make a new suggested edit model which stores a serialized hash for the new values.

**Comment by ArtOfCode-** [comment]
That sounds like a serious violation of database normalisation, which half defeats the point of a database. I'd *definitely* recommend a `edit_for` attribute on `RescueRequest`, now I think about it - a second model would just duplicate the request model, which is inefficient. We can use scopes to separate out suggested edits.

**Comment by izwick-schachter** [comment]
I've got no idea how to do that, but I thought a serialized diff would be fine. What's the issue with that?

**Comment by ArtOfCode-** [comment]
Perhaps we're thinking of different things... what do you mean by a serialized diff?

**Comment by izwick-schachter** [comment]
`new_values: {extra_details: "There's also 5 pets"}` with `serialize :new_values` in the model.

**Comment by ArtOfCode-** [comment]
Hmmm. Not quite what I thought, but still not entirely in line with normalisation. It'll work, though. Make it a polymorphic association, so that we can expand to suggested edits to other things in the future.

Generate command: `rails g model SuggestedEdit resource:references{polymorphic} user:references result:string reviewed_by_id:integer new_values:text`

**Comment by ArtOfCode-** [comment]
(That'll also let you add `belongs_to :reviewed_by, class_name: 'User'` to the model to track the results of suggested edit reviews).

**Comment by izwick-schachter** [comment]
What's the non-generator way to do this? I might have already started...

**Comment by ArtOfCode-** [comment]
What have you got so far?

**Comment by izwick-schachter** [comment]
I'll make a PR in a sec

**Comment by izwick-schachter** [comment]
See #29
