### ISSUE TITLE
Make edit notes formatted correctly

### ISSUE THREAD

**Issue by ArtOfCode-** [CrowdRescueHQ/CrowdRescue#21]
System case notes detailing edits to rescue requests aren't formatted correctly:

![case-note](https://user-images.githubusercontent.com/10406565/30523120-60a180c0-9bd3-11e7-89a9-00c372659022.png)

This requires HTML to format correctly, not `\n` joins, but doing that requires careful work to make sure there's no injection/XSS vulnerability.

While we're at it, we could ignore nil/empty being changed to nil/empty, and we can also ignore updated_at changing.

**Comment by izwick-schachter** [comment]
I think a simple `#gsub("\n", "<br>")` should work for the log formatting. I don't see a need to deal with nil/empty, but I can certainly fix it.

**Comment by izwick-schachter** [comment]
Case note formatting should be fixed in bdf26ac, and I'm working on the nil/empty thing now.

**Comment by izwick-schachter** [comment]
Now this should be fixed. @ArtOfCode- unless you've got a reason why the HTML should be stored in the DB instead of converted when rendering the view, this issue should be closed.
