### ISSUE TITLE
Unrestricted Update

### ISSUE THREAD

**Issue by izwick-schachter** [CrowdRescueHQ/CrowdRescue#22]
Anyone who knows the ID (which is given in the URL) can update a rescue request. We need to use the key field to restrict that to only people who have either 1) created it or 2) are authenticated.

**Comment by ArtOfCode-** [comment]
The key is useful for letting the unauthenticated creator edit the request, yes - but for authenticated users, we should just be using roles and letting anyone with a specific set of roles edit the request.

**Comment by ArtOfCode-** [comment]
We can probably give edit access to triage, medical, and admin/developer.

**Comment by ArtOfCode-** [comment]
We can also create a system that allows us to give specific users authorization to edit a request even if they don't have one of the required roles. That'll be more complex, though, and lower priority - I'll create a separate issue for that and self-assign for me to work on next week,
