### ISSUE TITLE
Restart Queues

### ISSUE THREAD

**Issue by izwick-schachter** [CrowdRescueHQ/CrowdRescue#23]
We need to restart queues development, and with a plan this time. Here's the structure:

Each rescue request has 2 new attributes, `dupe_of:integer` and `spam:boolean`.

There's a new `ReviewTask` table to log reviews.

When somone hits `/queues/spam` it pulls a random record with `RescueRequest.where(spam:nil).order("RAND()").first` (modified so it doesn't grab anything with a reviewtask already created), creates a reviewtask with no outcome marked and renders it with buttons below it "Spam", "Not Spam", "Skip". It then posts the name of the button to `/queues/spam/new` where a reviewtask is updated with the outcome, and it is marked either spam:true or spam:false.

When someone hits `/queues/dedupe` it pulls a random record that has no dedupe review tasks and is not a dupe. It then renders that record and all similar record vertically aligned, each possible dupe with a button next to it, each with a value of the id of that record. There's also a skip button at the bottom. Those are the differences between that and the spam queue.

**Comment by ArtOfCode-** [comment]
Why random? Why not most-recent-first (or most-recent-last)?

**Comment by izwick-schachter** [comment]
I'm concerned about 2 people getting the same review.

**Comment by ArtOfCode-** [comment]
There's no guarantee that won't  happen with random selection either, though. Instead, order by some other more logical order, and add a review_locked attribute to rescue requests that we use to indicate when someone is already doing that review.

**Comment by izwick-schachter** [comment]
But what if they start it and never finish?

**Comment by ArtOfCode-** [comment]
Add a time limit - if the review hasn't unlocked within 10 minutes, automatically unlock it. That also requires a check in the review submission action that the review is locked to the current user - if it's not, someone else might be doing it because of the auto-unlock.

**Comment by izwick-schachter** [comment]
It might be nice to add in some websockets e.g. to push "Another user completed this review" or "Another user edited this rescue request"
