### ISSUE TITLE
Rescue request table view

### ISSUE THREAD

**Issue by izwick-schachter** [CrowdRescueHQ/CrowdRescue#3]
We should add a RescueRequest table view that will show the values of some columns (e.g. name, case id, status) but hide other info behind a link labelled "Click to view more information. Access is logged.". That link should make a AJAX call to the backend where the request is logged in a PIIAccessEvents table and the values are returned.

**Comment by ArtOfCode-** [comment]
Done, look at [`rescue_requests#disaster_index`](https://github.com/CrowdRescueHQ/CrowdRescue/blob/master/app/controllers/rescue_requests_controller.rb#L15), [`AccessLog`](https://github.com/CrowdRescueHQ/CrowdRescue/blob/master/app/models/access_log.rb), and [`AccessLogger`](https://github.com/CrowdRescueHQ/CrowdRescue/blob/master/app/controllers/concerns/access_logger.rb).
