### ISSUE TITLE
Empty disaster throws error

### ISSUE THREAD

**Issue by izwick-schachter** [CrowdRescueHQ/CrowdRescue#32]

**Comment by ArtOfCode-** [comment]
...elaborate?

**Comment by izwick-schachter** [comment]
When you go to disaster_index, it throws an error if no requests have been created.

**Comment by ArtOfCode-** [comment]
Ah, gotcha

**Comment by ArtOfCode-** [comment]
Can't reproduce. What are you doing to get this error?

**Comment by izwick-schachter** [comment]
I might've forgotten to seed the db.

**Comment by ArtOfCode-** [comment]
That'd probably do it
