### ISSUE TITLE
Triage is status

### ISSUE THREAD

**Issue by shimpossible** [CrowdRescueHQ/CrowdRescue#36]
There triage field is really a status and should be renamed to such.  Actual triage is used to mark urgency.

**Comment by ArtOfCode-** [comment]
It *is* marked as status as far as I see. Can you clarify what you're looking at?

![selection_024](https://user-images.githubusercontent.com/10406565/31023718-a5b76124-a534-11e7-900e-81c072591323.png)

**Comment by ArtOfCode-** [comment]
Closing pending clarification

**Comment by shimpossible** [comment]
Yep.  I miss read rescue status as triage status
