### ISSUE TITLE
Edit improvements

### ISSUE THREAD

**Issue by ArtOfCode-** [CrowdRescueHQ/CrowdRescue#46]
We need to improve broadcast item edit functionality.

 - [x] Add a `belongs_to :user` association to `Broadcast::Item`.
 - [ ] Let authors of broadcast items edit them at any time
 - [ ] Let people with the (new) BroadcastReviewer role edit any item, any time.

**Comment by izwick-schachter** [comment]
>  Let authors of broadcast items edit them at any time

Is this not already true? Anyone with the correct roles can edit.

**Comment by izwick-schachter** [comment]
Oh! To confirm, you want me to take edit powers away from everyone and only let either authors or BroadcastReviewers edit?

**Comment by ArtOfCode-** [comment]
Yep, or developers/admins
