### ISSUE TITLE
Review Button

### ISSUE THREAD

**Issue by Lindavzisme** [CrowdRescueHQ/CrowdRescue#48]
Instead of "Finish" - replace with "Review" and show a summary with an edit option. Then on the Summary page, have a button that says "Submit Rescue Request".

I mean, on the Summary page, there are TWO options: "Edit Request" and "Submit Rescue Request".

**Comment by izwick-schachter** [comment]
Isn't this already the case? You click "Contine" and go to the page with your request. You can either edit or do nothing.
