### ISSUE TITLE
Two Content Boxes Side by Side

### ISSUE THREAD

**Issue by Lindavzisme** [CrowdRescueHQ/CrowdRescue#52]
A different "quick fix" that might be easier? On the Input form - show the Content box already open for the Spanish niput and don't "hide" it 

I'd really rather see - in the "View" page - the 2 content boxes side-by-side. Then, if there's no translation  - the box is empty!!!

**Comment by ArtOfCode-** [comment]
Completed by 1bb39b2c93fbd3bbbe9c6abb614369fd6644f58a
