### ISSUE TITLE
Task-flow for reviewing content. 

### ISSUE THREAD

**Issue by Lindavzisme** [CrowdRescueHQ/CrowdRescue#53]
per Meghan UX

https://crowdrescuehq.slack.com/archives/C77M927UL/p1507581524000053?thread_ts=1507578972.000312&cid=C77M927UL

**Comment by Lindavzisme** [comment]
Per Meghan

**Comment by izwick-schachter** [comment]
This link is to the following message:

> Task-flow for reviewing content. Better outputs for Broadcast. Sending content out to different media.

Can you please be more specific? This doesn't help us build anything. What would a better output be? What do you mean by "sending content out to different media"? What would a better task-flow for reviewing content be?

**Comment by Lindavzisme** [comment]
Moving to Project Wishlist Until Detail is Flushed Out
