### ISSUE TITLE
Better outputs for Broadcast

### ISSUE THREAD

**Issue by Lindavzisme** [CrowdRescueHQ/CrowdRescue#55]
per Meghan UX

https://crowdrescuehq.slack.com/archives/C77M927UL/p1507581524000053?thread_ts=1507578972.000312&cid=C77M927UL

**Comment by izwick-schachter** [comment]
This link is to the following message:

> Task-flow for reviewing content. Better outputs for Broadcast. Sending content out to different media.

By Meghan UX

Can you please be more specific? This doesn't help us build anything. What would a better output be? "Better" isn't very clear and in order for us to build something, we'd like to here *how* you think it could be better.

**Comment by Lindavzisme** [comment]
Moving to Project Wishlist Until Detail is Flushed Out
