### ISSUE TITLE
Data visualization

### ISSUE THREAD

**Issue by Lindavzisme** [CrowdRescueHQ/CrowdRescue#57]
per Christopher Bellmyer

https://crowdrescuehq.slack.com/archives/C77M927UL/p1507581658000088?thread_ts=1507578972.000312&cid=C77M927UL

**Comment by ArtOfCode-** [comment]
This and #58 are more likely to be done with specialist tools outside of SCOT, but there may be some stuff we can do.

**Comment by izwick-schachter** [comment]
That links to the following message:

> Data visualization and GIS mapping, here, but that’s just me.

By Chris B.

What are some types of data visualization you'd like to see? We're talking about integration with ArcGIS, but do you have any specific requests?

**Comment by Lindavzisme** [comment]
Moving to Project Wishlist Until Detail is Flushed Out
