### ISSUE TITLE
GIS mapping

### ISSUE THREAD

**Issue by Lindavzisme** [CrowdRescueHQ/CrowdRescue#58]
per Christopher Bellmyer and thesecretmaster
https://crowdrescuehq.slack.com/archives/C77M927UL/p1507581658000088?thread_ts=1507578972.000312&cid=C77M927UL

https://crowdrescuehq.slack.com/archives/C77M927UL/p1507583686000388?thread_ts=1507578972.000312&cid=C77M927UL

**Comment by izwick-schachter** [comment]
This links to the following messages:

> Data visualization and GIS mapping, here, but that’s just me.

By Chris B.

> This sounds awesome! I'd love to figure out better ways to connect SCOT to data viz, and improve SCOT to fill other gaps.

By thesecretmaster

Do you have any _ideas_ for better ways?

**Comment by Lindavzisme** [comment]
Moving to Project Wishlist Until Detail is Flushed Out

**Comment by Tensibai** [comment]
Adding this here to avoid spamming, but could Whishlist be a milestone without end date to affect issues to be discussed instead of closing where they'll be forgiven on short term?

**Comment by ArtOfCode-** [comment]
Wishlist is a project, @Tensibai; stuff that still needs discussion will be discussed in Slack

**Comment by Tensibai** [comment]
Aww I did misunderstood the closure message as moving the issue to an unknown tag where it's a different project, sorry for the noise :/

**Comment by ArtOfCode-** [comment]
No worries :)
