### ISSUE TITLE
Better flow from a personal view of the victim of an event to safety options and resources

### ISSUE THREAD

**Issue by Lindavzisme** [CrowdRescueHQ/CrowdRescue#59]
per kayleefrye

https://crowdrescuehq.slack.com/archives/C77M927UL/p1507584066000136?thread_ts=1507578972.000312&cid=C77M927UL

**Comment by izwick-schachter** [comment]
Can you clarify what that flow would be? Saying it should be "better" doesn't help us improve SCOT.
