### ISSUE TITLE
Reduce Duplicate Entries

### ISSUE THREAD

**Issue by Lindavzisme** [CrowdRescueHQ/CrowdRescue#60]
per Meghan UX

Some way to reduce duplicate entries (stop them from getting made), which probably means seeing some details about other entries. Like - we've received other requests from that general area, could these be the same? - type of queries.

https://crowdrescuehq.slack.com/archives/C77M927UL/p1507588260000280?thread_ts=1507578972.000312&cid=C77M927UL

**Comment by ArtOfCode-** [comment]
Duplicate of #47
