### ISSUE TITLE
Flow charts for volunteers to know what does where and who does what

### ISSUE THREAD

**Issue by Lindavzisme** [CrowdRescueHQ/CrowdRescue#62]
per Lynn

https://crowdrescuehq.slack.com/archives/C77M927UL/p1507588348000191?thread_ts=1507578972.000312&cid=C77M927UL

**Comment by ArtOfCode-** [comment]
This is an org-wide thing, rather than a SCOT thing

**Comment by Lindavzisme** [comment]
Sorry, please don't close this. We have not defined what this is yet and may be part of the broader 'volunteer' management.

**Comment by Tensibai** [comment]
This sounds more part of a linked documentation project than the application itself. Should the documentation be part of the application?

This has a positive: any change should go through a pull request and be reviewed
And a negative : It needs a professional technical writer to review them so there's nothing misleading included
