### ISSUE TITLE
Hide deprecate and edit links on public broadcast links

### ISSUE THREAD

**Issue by izwick-schachter** [CrowdRescueHQ/CrowdRescue#75]
Even if you're not logged in, through the broadcast viewer you see the edit and depricate links.

**Comment by MeghanUX** [comment]
Agree. Deprecate and edit links only to "logged in" users.

**Comment by izwick-schachter** [comment]
Will do by moving the elements to the view and only modifying those elements using JS, as soon as #79 is merged.
