### ISSUE TITLE
Any user (without any roles) can make translation requests

### ISSUE THREAD

**Issue by izwick-schachter** [CrowdRescueHQ/CrowdRescue#78]
Anyone who creates an account can spam translation requests. This seems like it shouldn't be allowed.

**Comment by ArtOfCode-** [comment]
That was deliberate, not a bug. I don't really want to have to add permissions to literally every user just so they can fire a translation request. Any abusive accounts we can just nuke. Objections?

**Comment by izwick-schachter** [comment]
Nope
