### ISSUE TITLE
Need a data scrape - sources + Municipality

### ISSUE THREAD

**Issue by MeghanUX** [CrowdRescueHQ/CrowdRescue#89]
Hi, we are starting a project to list all the resources we are accessing to create a list. Also agencies we are working with, etc. 

Can you scrape the data from Scot to provide us with a spreadsheet (or cvs file) that includes:
- source info
- linked to Municipality
- optional: name of person who input it (so we can follow up with questions, if needed)

This is needed by a small group in a locked channel. Best to deliver to one of or all of: Indigo Sky, Lynn, Arrow, Lotus, Melissa Hafter, Nick Walker, Alex or myself (there are more, but this is a good sub-set).

Thanks!

**Comment by ArtOfCode-** [comment]
Completed
